
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRECH ABREPAR ALERTA BOOL DESLIGAR DISPOSITIVO DOISPT E ENTAO ENVIAR FECHACH FECHAPAR ID IGUAL LIGAR NUM OPLOGIC PARA PONTO SE SENAO SET STRING TODOS VIRGprogram : devices cmdsdevices : device devices\n| devicedevice : DISPOSITIVO DOISPT ABRECH ID FECHACH\n| DISPOSITIVO DOISPT ABRECH ID VIRG ID FECHACHcmds : cmd PONTO cmds\n| cmd PONTOcmd : atrib\n| obsact\n| actatrib : SET ID IGUAL varvar : NUM\n| BOOLobsact : SE obs ENTAO actobsact : SE obs ENTAO act SENAO actobs : ID OPLOGIC varobs : ID OPLOGIC var E obsact : LIGAR IDact : DESLIGAR IDact : ENVIAR ALERTA ABREPAR STRING FECHAPAR IDact : ENVIAR ALERTA ABREPAR STRING VIRG ID FECHAPAR IDact : ENVIAR ALERTA ABREPAR STRING FECHAPAR PARA TODOS DOISPT id_listact : ENVIAR ALERTA ABREPAR STRING VIRG ID FECHAPAR PARA TODOS DOISPT id_listid_list : ID VIRG id_list\n| ID'
    
_lr_action_items = {'DISPOSITIVO':([0,3,37,49,],[4,4,-4,-5,]),'$end':([1,5,17,25,],[0,-1,-7,-6,]),'SET':([2,3,15,17,37,49,],[10,-3,-2,10,-4,-5,]),'SE':([2,3,15,17,37,49,],[11,-3,-2,11,-4,-5,]),'LIGAR':([2,3,15,17,27,37,39,49,],[12,-3,-2,12,12,-4,12,-5,]),'DESLIGAR':([2,3,15,17,27,37,39,49,],[13,-3,-2,13,13,-4,13,-5,]),'ENVIAR':([2,3,15,17,27,37,39,49,],[14,-3,-2,14,14,-4,14,-5,]),'DOISPT':([4,50,57,],[16,52,59,]),'PONTO':([6,7,8,9,21,22,31,32,33,34,44,46,53,55,56,60,61,],[17,-8,-9,-10,-18,-19,-11,-12,-13,-14,-15,-20,-21,-22,-25,-24,-23,]),'ID':([10,11,12,13,24,38,40,41,42,51,52,58,59,],[18,20,21,22,30,43,20,46,48,53,56,56,56,]),'ALERTA':([14,],[23,]),'ABRECH':([16,],[24,]),'IGUAL':([18,],[26,]),'ENTAO':([19,32,33,35,45,],[27,-12,-13,-16,-17,]),'OPLOGIC':([20,],[28,]),'SENAO':([21,22,34,46,53,55,56,60,61,],[-18,-19,39,-20,-21,-22,-25,-24,-23,]),'ABREPAR':([23,],[29,]),'NUM':([26,28,],[32,32,]),'BOOL':([26,28,],[33,33,]),'STRING':([29,],[36,]),'FECHACH':([30,43,],[37,49,]),'VIRG':([30,36,56,],[38,42,58,]),'E':([32,33,35,],[-12,-13,40,]),'FECHAPAR':([36,48,],[41,51,]),'PARA':([41,51,],[47,54,]),'TODOS':([47,54,],[50,57,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'devices':([0,3,],[2,15,]),'device':([0,3,],[3,3,]),'cmds':([2,17,],[5,25,]),'cmd':([2,17,],[6,6,]),'atrib':([2,17,],[7,7,]),'obsact':([2,17,],[8,8,]),'act':([2,17,27,39,],[9,9,34,44,]),'obs':([11,40,],[19,45,]),'var':([26,28,],[31,35,]),'id_list':([52,58,59,],[55,60,61,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> devices cmds','program',2,'p_program','obsact_parser.py',9),
  ('devices -> device devices','devices',2,'p_devices','obsact_parser.py',35),
  ('devices -> device','devices',1,'p_devices','obsact_parser.py',36),
  ('device -> DISPOSITIVO DOISPT ABRECH ID FECHACH','device',5,'p_device','obsact_parser.py',40),
  ('device -> DISPOSITIVO DOISPT ABRECH ID VIRG ID FECHACH','device',7,'p_device','obsact_parser.py',41),
  ('cmds -> cmd PONTO cmds','cmds',3,'p_cmds','obsact_parser.py',49),
  ('cmds -> cmd PONTO','cmds',2,'p_cmds','obsact_parser.py',50),
  ('cmd -> atrib','cmd',1,'p_cmd','obsact_parser.py',57),
  ('cmd -> obsact','cmd',1,'p_cmd','obsact_parser.py',58),
  ('cmd -> act','cmd',1,'p_cmd','obsact_parser.py',59),
  ('atrib -> SET ID IGUAL var','atrib',4,'p_atrib','obsact_parser.py',63),
  ('var -> NUM','var',1,'p_var','obsact_parser.py',68),
  ('var -> BOOL','var',1,'p_var','obsact_parser.py',69),
  ('obsact -> SE obs ENTAO act','obsact',4,'p_obsact_se_entao','obsact_parser.py',73),
  ('obsact -> SE obs ENTAO act SENAO act','obsact',6,'p_obsact_se_entao_senao','obsact_parser.py',77),
  ('obs -> ID OPLOGIC var','obs',3,'p_obs_obs_oplogic_var','obsact_parser.py',81),
  ('obs -> ID OPLOGIC var E obs','obs',5,'p_obs_and','obsact_parser.py',85),
  ('act -> LIGAR ID','act',2,'p_act_ligar','obsact_parser.py',89),
  ('act -> DESLIGAR ID','act',2,'p_act_desligar','obsact_parser.py',93),
  ('act -> ENVIAR ALERTA ABREPAR STRING FECHAPAR ID','act',6,'p_act_enviar_alerta_msg_device','obsact_parser.py',97),
  ('act -> ENVIAR ALERTA ABREPAR STRING VIRG ID FECHAPAR ID','act',8,'p_act_enviar_alerta_msg_var_device','obsact_parser.py',101),
  ('act -> ENVIAR ALERTA ABREPAR STRING FECHAPAR PARA TODOS DOISPT id_list','act',9,'p_act_enviar_alerta_msg_para_todos','obsact_parser.py',105),
  ('act -> ENVIAR ALERTA ABREPAR STRING VIRG ID FECHAPAR PARA TODOS DOISPT id_list','act',11,'p_act_enviar_alerta_msg_var_para_todos','obsact_parser.py',113),
  ('id_list -> ID VIRG id_list','id_list',3,'p_id_list','obsact_parser.py',121),
  ('id_list -> ID','id_list',1,'p_id_list','obsact_parser.py',122),
]
